name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest  #ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: latamchallenge-apideploy

      - name: Deploy to GCP
        run: |
          gunicorn -w 4 --timeout 0 -k uvicorn.workers.UvicornWorker api:app

