name: 'Continuous Integration'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest #ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10

    - name: Create virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install -r requirements-dev.txt
        python -m pip install -r requirements-test.txt
        python -m pip install -r requirements.txt

    - name: Build
      run: |
        make build

    - name: Run tests
      run: |
        make model-test
        make api-test
        make stress-test

    

    
